services:
    spizza_user.registration.form.type:
        class: SPizza\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: spizza_user_registration }
